[package]
name = "rustp2p"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.9", features = ["derive"] }
log = "0.4.22"
tokio = { version = "1.38.0", features = ["full"] }

[dev-dependencies]
clippy = "0.0.302"
